import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastProvider } from "@/components/ui/toast";
import "./globals.css";
import { ToastViewport } from "@/components/ui/toast";
import { RemoveExtensionAttributes } from "@/components/ui/remove-extension-attributes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Le composant RemoveExtensionAttributes a été déplacé dans un fichier séparé
// pour pouvoir utiliser la directive 'use client'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans`} suppressHydrationWarning>
        <ToastProvider>
          {children}
          <ToastViewport />
          <RemoveExtensionAttributes />
        </ToastProvider>
      </body>
    </html>
  );
}
